nodeLinker: pnp

npmRegistries:
  //npm.pkg.github.com:
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_TOKEN}

npmScopes:
  dracula:
    npmRegistryServer: "https://npm.pkg.github.com/"

yarnPath: .yarn/releases/yarn-3.0.2.cjs
